version: '3'

services:
  fairwear-db2:
    image: postgres:15
    restart: always
    container_name: db-fairwear
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fairwear
    ports: 
      - '5432:5432'
    volumes:
      - .db:/var/lib/postgresql/

  fairwear-db:
    image: postgres:15
    restart: always
    container_name: db-
    hostname: test-postgres
    environment:
      POSTGRES_USER: fairwear
      POSTGRES_PASSWORD: fairwear
      POSTGRES_DB: fairwear
    ports:
      - '5435:5432'
    volumes:
      - .db:/var/lib/postgresql/
